# COMMANDS FOR ROBOT
CMD_ROBOT_STOP				= '1'
CMD_ROBOT_SLOW				= '2'
CMD_ROBOT_RESET_COUNT		= '3'
CMD_DISPLAY_EMERGENCY = '4'
CMD_DISPLAY_PROBLEM = '5'
CMD_DISPLAY_PROCEED = '6'
CMD_RESET_EMERGENCY = '7'
CMD_DISPLAY_STOP = '8'

# COMMANDS FOR ARDUINO
CMD_DEV_RESET = '1'
CMD_DEV_COUNT = '2'
CMD_DEV_DISPLAY_EMERGENCY = '4'
CMD_DEV_DISPLAY_PROBLEM = '5'
CMD_DEV_DISPLAY_PROCEED = '6'
CMD_DEV_RESET_EMERGENCY = '7'
CMD_DEV_DISPLAY_STOP = '8'
CMD_DEV_EMERGENCY_FLAG = '9'
